### ISSUE TITLE
Error during task execution

### ISSUE THREAD

**Issue by CPZCPZ** [PathPlanning/ORCA-algorithm#3]
Hi ! Sorry to disturb you. 
Your projects and papers are great ! I successfully compiled the project according to your readme file, but there was an error as shown in the title during execution.  Then I set FullOutput to ON in the CmakeList file, and the prompts are as follows. 
`./Single ../../TaskExamples/1_task.xml 10`
`searchtype element not found in XML file. It was defined to thetastar`
`mapfnum element not found in XML file. It was defined to 3`
`reps element not found at default_parameters tag. It was defined to 0.15`
`start.theta element not found in XML file at agent 0 It was defined to 0`
`Error during task execution`
What causes the function `task.ReadTask ( )` in SingleTest.cpp return false, could you explain it.  Thank you very much for your time.

**Comment by haiot4105** [comment]
Hi!. 

I apologize for the late response. The described error was caused by a bug related to reading the initial angles `theta` of agents that using by a differential drive dynamic model in ORCA for differential drive robots (implemented in `ORCADDAgent.h` and `ORCADDAgent.cpp`). In other cases, the initial angle is not taken into account, but when reading the file, it was still required to specify it. 

This bug has been fixed and at the moment the code should run even if the initial angles of the agents are not specified in the task file. 

Thank you for pointing out the error!

**Comment by ManishBansiwal29** [comment]
Hello...!
I am facing when i am trying to compile this on my local pc i am getting these errors i am attaching a screenshot please help me out how to solve these errors
![Screenshot from 2024-03-14 01-43-39](https://github.com/PathPlanning/ORCA-algorithm/assets/52676528/dca4369d-96f6-4420-b091-daf92cdc0353)
